export enum HttpStatusCodes {
  OK = 200,
  CREATED = 201,
  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,
  METHOD_NOT_ALLOWED = 405,
  INTERNAL_SERVER_ERROR = 500,
}

export const messages = {
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  UNAUTHORIZED: 'UNAUTHORIZED',
  REQUIRED_USERNAME: 'REQUIRED_USERNAME',
  REQUIRED_EMAIL: 'REQUIRED_EMAIL',
  REQUIRED_PASSWORD: 'REQUIRED_PASSWORD',
  REQUIRED_CONFIRM_PASSWORD: 'REQUIRED_CONFIRM_PASSWORD',
  REQUIRED_TOKEN: 'REQUIRED_TOKEN',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_EMAIL: 'INVALID_EMAIL',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  INVALID_CONFIRM_PASSWORD: 'INVALID_CONFIRM_PASSWORD',
  INVALID_CODE: 'INVALID_CODE',
  EXPIRED_CODE: 'EXPIRED_CODE',
  PENDING_VERIFICATION: 'PENDING_VERIFICATION',
};

export const regexp = {
  PASSWORD: new RegExp('^[a-zA-Z0-9]{6,}$'),
  HEX_COLOR: new RegExp('^#([A-F0-9]{3,4}|[A-F0-9]{6}|[A-F0-9]{8})$', 'i'),
};

export const roles = {
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
};
